<a href="https://colab.research.google.com/github/kavithabantupalli/Python_basic/blob/main/Phase2ACCENTURE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Check whether a character is a vowel or consonant**

In [ ]:
s=input()
vowel="aeiouAEIOU"

if s in vowel:
  print("The character is a vowel")
else:
  print("The character is a consonant ")''
.


n
The character is a consonant 


**check whether a character is a alphabet or not**

In [ ]:
s=input()
#x="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
#if s.isalpha():
if s>='a' and s<='z' or s>='A' and s<='Z':
#if s in x:
  print("The character is a alphabet")
else:
  print("The character is not a alphabet")

a
The character is a alphabet


**find the ascii value of a character**


In [ ]:
s=input()
print(ord(s))

F
70


**Toggle each character in a string**

In [ ]:
s=input()
#x=s.swapcase()
#print(x)
for i in s:
  if i.isupper():
    print(i.lower(),end="")
  else:
    print(i.upper(),end="")

KaVIth
kAviTH

**Count the number of vowels in string**

In [ ]:
s=input()
vowel="aeiouAEIOU"

count=0
for i in s:
  if i in vowel:
    count=count+1
print(count)

kavi
2


**length of the string without using strlen() function**

In [ ]:
s=input()
count=0
for i in s:
  count=count+1
print(count)

kavitha
7


**remove the vowels from a string**

In [ ]:
s=input()
vowel="aeiouAEIOU"
list=[]
for i in s:
  if i not in vowel:
    list.append(i)
print(''.join(list))

kavitha
kvth


**check if the given string is palindrom or not**

In [ ]:
s=input()
if s==s[::-1]:
  print("The string is palindrom")
else:
  print("The string is not palindrom")

mam
The string is palindrom


**print the given string in reverse order**

In [ ]:
s=input()
rev=s[::-1]
print(rev)

kavi
ivak


**remove all characters from string except alphabets**

In [ ]:
s=input()
li=[]
for i in s:
  if i>='a' and i<='z' or i>='A' and i<='Z':
    li.append(i)
print(''.join(li))

kavi@tha14
kavitha


**remove space from  a string**

In [ ]:
s=input()
li=[]
for i in s:
  if i!=' ':
    li.append(i)
print(''.join(li))

kavi tha 
kavitha


In [ ]:
print("kavi","th" "a")

kavi tha


**remove brackets from an algebraic expression**

**count the sum of numbers in the string**

In [ ]:
s=input()
sum=0
for i in s:
  if i.isdigit():
    sum=sum+int(i)

print(sum)

kavi14
5


**PATTERNS**

In [ ]:
x=int(input())
for row in range(x):
    print("*"*x)



5
*****
*****
*****
*****
*****


In [ ]:
#hollow sphere
x=int(input())
for i in range(x):
  for j in range(x):
    if i==0 or i==x-1 or j==0 or j==x-1:
        print("*",end=" ")
    else:
      print(" ",end=" ")
  print()


5
* * * * * 
*       * 
*       * 
*       * 
* * * * * 


In [ ]:
#triangle
x=int(input())
for i in range(1,x+1):
  print("*"*i)



5
*
**
***
****
*****


In [ ]:
x=int(input())
for i in range(1,x+1):
  print(" "*(x-i),"*"*i)

5
     *
    **
   ***
  ****
 *****


In [ ]:
x=int(input())
for i in range(1,x+1):
  print("*"*(x-i)," "*i)

5
****  
***   
**    
*     
      


In [ ]:
x=int(input())
for i in range(1,x+1):
  for j in range(1,x+1):
    if j==1 or i==x or i==j:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

5
*         
* *       
*   *     
*     *   
* * * * * 


In [ ]:
#remove the repate char and reverse the str print it
s=input()
li=[]
for i in s:
  if i not in li:
    li.append(i)
print(''.join(li[::-1]))




kavitha
htivak


In [ ]:
#convert uppercase letters into lowercase,remove non-alphabetical letters,string reverse like palindrome
x=input()
li=[]
x=x.lower()
for i in x:
  if i>='a' and i<='z':
    li.append(i)
print(''.join(li[::-1]))

or i in range(len(x)-k+1):
  print(max(x[i:i+k]))



Mad@am
madam


In [ ]:
#print the palindrom numbers between the lowerlimit and upperlimit
a=int(input())
b=int(input())
for i in range(a,b):
  x=str(i)
  if x==x[::-1]:
    print(i,end=" ")

10
80
11 22 33 44 55 66 77 

In [ ]:
#given an array and an integer k, find the maximum for each and every contiguous subarray of size k.



**NUMPY**

In [ ]:
#single dimenional array in python
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.dtype)

[1 2 3 4 5]
(5,)
int64


In [ ]:
#two dimentional array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
#multi dimenional array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.shape)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
int64


In [ ]:
#three  dimenional array
import numpy as np
arr=np.array([[[1,2,3],[3,4,5],[4,6,9]]])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)



[[[1 2 3]
  [3 4 5]
  [4 6 9]]]
<class 'numpy.ndarray'>
(1, 3, 3)
int64


In [ ]:
#create the 1D,2D of array and find shape ,type of an array for integer,float
#1D array
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print("-----------------------------------")

#2D array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1.shape)
print("----------------------------------")

#1D array for float type
arr2=np.array([1.2,2.3,3.4,4.5])
print(arr2)
print(type(arr2))
print(arr2.dtype)
print(arr2.shape)
print("----------------------------------")

#2D array for float type
arr3=np.array([[1.2,2.3,3.4,4.4],[5.6,4.6,2.3,7.8]])
print(arr3)
print(type(arr3))
print(arr3.dtype)
print(arr3.shape)


[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
-----------------------------------
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
----------------------------------
[1.2 2.3 3.4 4.5]
<class 'numpy.ndarray'>
float64
(4,)
----------------------------------
[[1.2 2.3 3.4 4.4]
 [5.6 4.6 2.3 7.8]]
<class 'numpy.ndarray'>
float64
(2, 4)


In [ ]:
#numpy reshape
import numpy as np
arr=np.array([1,2,3,4,5,6])
a=arr.reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#numpy indexing


**ACCENTURE CODE**

In [ ]:
#take two input strings str1 and str2 ,if str1 is rearrange then it should be equal to str2
str1=input()
str2=input()
if sorted(str1)==sorted(str2):
  print("true")
else:
  print("false")

listen
silent
true


In [ ]:
#take a input string and find out the length of each word and print the max length of word
s=input()
lit=s.split()
long=""
for i in lit:
  cur=i
  if len(cur)>len(long):
    long=cur
print(long)




In [ ]:
#convert 15 into binary and add the digits output:4
x=int(input())
binary=bin(x).replace("0b","")
sum=0
for i in binary:
  if i=='1' or i=='0':
    sum=sum+1
print(sum)
print(binary)



15
4
1111


In [ ]:
#print the numbers  in triangle pattern

n = int(input())
num = 1
for i in range(n):
  for j in range(i + 1):
    print(num, end=" ")
    num += 1
  print()




4
1 
2 3 
4 5 6 
7 8 9 10 


**Searching techniques**

In [ ]:
#search the element in the arr
'''
a=3,4,1,88,63,9,7
s=63
'''
arr=map(int,input().split(","))
s=int(input())
for i in arr:
  if i==s:
    print("element found")
    break
else:
  print("elment not found")

3,4,1,88,63,9,7
63
element found


In [ ]:
#linear search
arr=map(int,input().split(","))
s=int(input())
index=0
for i in arr:
  if i==s:
    print("element found at index",index)
    break
  index+=1
else:
  print("elment not found")

3,4,1,88,63,9,7
63
element found at index 4


In [ ]:
#binary  search 2,3,6,8,12,15,20  find 12
arr =list(map(int, input().split(",")))
s =int(input())
low = 0
high = len(arr)-1
index = -1

while low <= high:
  mid = (low + high) // 2
  if arr[mid] == s:
    print("element found at index", mid)
    break
  elif arr[mid] < s:
    low = mid + 1
  else:
    high = mid - 1
    mid=(low+high)//2
else:
  print("element not found")